CC = swiftc

NAME = seaBattle

SRC =   SymbolMap.swift Map.swift Filler.swift AIStepper.swift Stepper.swift ParsStepper.swift \
		Menu.swift Player.swift PrinterGame.swift InputPlayer.swift\
			PrintConsoleGame.swift LogGame.swift Settings.swift\
			RandomFillField.swift Game.swift main.swift Logger.swift ANSIColors.swift MenuText.swift SettingsText.swift

all:
	$(CC) $(SRC)
