CC = swiftc

NAME = seaBattle

SRC =   SymbolMap.swift Map.swift Filler.swift AIStepper.swift Stepper.swift ParsStepper.swift \
		Player.swift PrinterGame.swift MainMenu.swift\
			PrintConsoleGame.swift LogGame.swift\
			RandomFillField.swift Game.swift main.swift Logger.swift

all:
	$(CC) $(SRC)
