CC = swiftc

NAME = seaBattle

SRC =   SymbolMap.swift Map.swift Filler.swift AIStepper.swift Stepper.swift ParsStepper.swift \
		Menu.swift Player.swift PrinterGame.swift InputPlayer.swift Validate.swift\
			PrintConsoleGame.swift LogGame.swift Settings.swift ShotValue.swift \
			RandomFillField.swift Game.swift main.swift Logger.swift ANSIColors.swift MenuText.swift SettingsText.swift

all:
	$(CC) $(SRC)
